// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skvwymuejgimyctfdkve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrdnd5bXVlamdpbXljdGZka3ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NTQ0OTIsImV4cCI6MjA2NDEzMDQ5Mn0.VW__LMnaWgtwQoDfKkHZrx2TKXIOauyMQckA_Vf7dVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});